name: versaoteste
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logger: ^1.0.0

  flutter_local_notifications: ^18.0.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # Autenticação com provedores
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.1.1

  # Gerenciamento de estado
  provider: ^6.1.2

  # Outros utilitários
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  _flutterfire_internals: ^1.3.46
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  firebase_auth_platform_interface: ^7.4.9
  firebase_auth_web: ^5.13.4
  firebase_storage_platform_interface: ^5.1.33
  firebase_storage_web: ^3.10.5
  flutter_facebook_auth_platform_interface: ^6.1.2
  flutter_facebook_auth_web: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_secure_storage_windows: ^3.1.2
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0


flutter:
  uses-material-design: true
