name: versaoteste
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7

  # Autenticação
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Utilitários
  intl: ^0.20.1
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true